#write a program to input eight number from the users and dispaly all the unique number once.
s= set()
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
n = input("Enter the number : ")
s.add(int(n))
print(s)