a = input("Enter any number")
#if we use (""It is a string "")
b= input("Enter any number")
print(" Ther value of a is ",a)
print("The value of b is ",b)
print("The sum of a+ b is = ",a+b)
# converting the given string into int
a= int(input("Enter a number"))
b= int(input("Enter a number"))
print("The sum is ", a+b)